# -*- coding: utf-8 -*-
"""helloworld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Ur8Cb43MBQLGWNxaO3DxLqD8UEncwf7
"""

print("Hello World")

x = input("Hello " )
print(f"Hello {x}")

"""# **>>> Exercícios**
---
1.   Crie seu primeiro programa em Python printando uma mensagem de sua escolha.
"""

var = input("Larri ")
print(f"Larri {var}")

from google.colab import drive
drive.mount('/content/drive')